
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cities-db
    username: admin
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false